Refactor OS detection into separate scripts.

diff --git a/calculate-integral b/calculate-integral
--- a/calculate-integral
+++ b/calculate-integral
@@ -2,35 +2,26 @@
 
 # Copyright (c) 2018, Gabriel Johnson. All rights reserved.
 
-case $(uname) in
-    Linux)
-        wolfram=/usr/local/bin/MathKernel
-        ccl=ccl/lx86cl64
-        ;;
-    CYGWIN_NT-*) # Windows + Cygwin
-        wolfram=("/cygdrive/c/Program Files/Wolfram Research/Mathematica"/*/wolfram)
-        ccl=ccl/wx86cl64
-        ;;
-    MINGW*_NT-*) # Windows + Git Bash
-        wolfram=("/c/Program Files/Wolfram Research/Mathematica"/*/wolfram)
-        ccl=ccl/wx86cl64
-        ;;
-    Darwin) # Mac OS X
-        wolfram=/Applications/Mathematica.app/Contents/MacOS/MathKernel
-        ccl=ccl/dx86cl64
-        ;;
-    *)
-        echo "$0: Error: Unsupported operating system.">&2
-        exit 1
-        ;;
-esac
+cd $(dirname "${BASH_SOURCE[0]}")
+
+ccl="$(src/ccl-name)"
+
+if [ ! $? -eq 0 ]; then
+    echo "$0: fatal: No compatible CCL version found.">&2
+    exit 1
+fi
+
+wolfram="$(src/wolfram-path)"
+
+if [ ! $? -eq 0 ]; then
+    echo "$0: fatal: Cannot determine where to find Mathematica.">&2
+    exit 1
+fi
 
 test -f "$wolfram" || {
     echo "$0: Error: Mathematica kernel not found.">&2
     exit 1
 }
-
-cd $(dirname "${BASH_SOURCE[0]}")
 
 "$ccl" -I hkm.image $*\
   | "$wolfram" -noprompt\
diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -2,36 +2,26 @@
 
 # Copyright (c) 2018, Gabriel Johnson. All rights reserved.
 
-case $(uname) in
-    Linux)
-        kernel_path=/usr/local/bin/MathKernel
-        ccl=ccl/lx86cl64
-        ;;
-    CYGWIN_NT-*) # Windows + Cygwin
-        kernel_path=("/cygdrive/c/Program Files/Wolfram Research/Mathematica"/*/wolfram)
-        ccl=ccl/wx86cl64
-        ;;
-    MINGW*_NT-*) # Windows + Git Bash
-        kernel_path=("/c/Program Files/Wolfram Research/Mathematica"/*/wolfram)
-        ccl=ccl/wx86cl64
-        ;;
-    Darwin) # Mac OS X
-        kernel_path=/Applications/Mathematica.app/Contents/MacOS/MathKernel
-        ccl=ccl/dx86cl64
-        ;;
-    *)
-        echo "$0: Error: Unsupported operating system.">&2
-        exit 1
-        ;;
-esac
+cd $(dirname "${BASH_SOURCE[0]}")
+
+ccl="$(src/ccl-name)"
+
+if [ ! $? -eq 0 ]; then
+    echo "$0: fatal: No compatible CCL version found.">&2
+    exit 1
+fi
+
+kernel_path="$(src/wolfram-path)"
+
+if [ ! $? -eq 0 ]; then
+    echo "$0: Warning: Cannot determine where to find Mathematica.">&2
+fi
 
 test -f "$kernel_path" || {
     echo "$0: Warning: Mathematica kernel not found.">&2
     echo "Numerical values for the Hilbert-Kunz multiplicity and F-signature"\
          "cannot be calculated." >&2
 }
-
-cd $(dirname "${BASH_SOURCE[0]}")
 
 test -f src/spiroffs-project.lisp || {
     echo "$0: Source code not found. Cannot compile." >&2
