Have scripts find paths for Mathematica and CCL based on OS

diff --git a/calculate-integral b/calculate-integral
--- a/calculate-integral
+++ b/calculate-integral
@@ -2,11 +2,29 @@
 
 # Copyright (c) 2018, Gabriel Johnson. All rights reserved.
 
-#ccl=ccl/dx86cl64
-ccl=ccl
+case $(uname) in
+    Linux)
+        wolfram=/usr/local/bin/MathKernel
+        ccl=ccl/lx86cl64
+        ;;
+    CYGWIN_NT-*) # Windows + Cygwin
+        wolfram=("/cygdrive/c/Program Files/Wolfram Research/Mathematica"/*/wolfram)
+        ccl=ccl/wx86cl64
+        ;;
+    MINGW*_NT-*) # Windows + Git Bash
+        wolfram=("/c/Program Files/Wolfram Research/Mathematica"/*/wolfram)
+        ccl=ccl/wx86cl64
+        ;;
+    Darwin) # Mac OS X
+        wolfram=/Applications/Mathematica.app/Contents/MacOS/MathKernel
+        ccl=ccl/dx86cl64
+        ;;
+    *)
+        echo "$0: Error: Unsupported operating system.">&2
+        exit 1
+        ;;
+esac
 
-#wolfram=/Applications/Mathematica.app/Contents/MacOS/MathKernel
-wolfram=/usr/local/bin/MathKernel
 test -f "$wolfram" || {
     echo "$0: Error: Mathematica kernel not found.">&2
     exit 1
