Have scripts find paths for Mathematica and CCL based on OS

diff --git a/calculate-integral b/calculate-integral
--- a/calculate-integral
+++ b/calculate-integral
@@ -2,11 +2,25 @@
 
 # Copyright (c) 2018, Gabriel Johnson. All rights reserved.
 
-#ccl=ccl/dx86cl64
-ccl=ccl
+case $(uname) in
+    Linux)
+        wolfram=/usr/local/bin/MathKernel
+        ccl=ccl/lx86cl64
+        ;;
+    CYGWIN_NT-[[:digit:]]*.[[:digit:]]*)
+        wolfram="$(cygpath 'C:\Program Files\Wolfram Research\Mathematica\11.3\MathKernel')"
+        ccl=ccl/wx86cl64
+        ;;
+    Darwin)
+        wolfram=/Applications/Mathematica.app/Contents/MacOS/MathKernel
+        ccl=ccl/dx86cl64
+        ;;
+    *)
+        echo "$0: Error: Unsupported operating system.">&2
+        exit 1
+        ;;
+esac
 
-#wolfram=/Applications/Mathematica.app/Contents/MacOS/MathKernel
-wolfram=/usr/local/bin/MathKernel
 test -f "$wolfram" || {
     echo "$0: Error: Mathematica kernel not found.">&2
     exit 1
diff --git a/inequalities b/inequalities
--- a/inequalities
+++ b/inequalities
@@ -2,8 +2,21 @@
 
 # Copyright (c) 2018, Gabriel Johnson. All rights reserved.
 
-ccl=ccl/dx86cl64
-#ccl=ccl
+case $(uname) in
+    Linux)
+        ccl=ccl/lx86cl64
+        ;;
+    CYGWIN_NT-[[:digit:]]*.[[:digit:]]*)
+        ccl=ccl/wx86cl64
+        ;;
+    Darwin)
+        ccl=ccl/dx86cl64
+        ;;
+    *)
+        echo "$0: Error: Unsupported operating system.">&2
+        exit 1
+        ;;
+esac
 
 cd $(dirname "${BASH_SOURCE[0]}")
 
diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -2,8 +2,24 @@
 
 # Copyright (c) 2018, Gabriel Johnson. All rights reserved.
 
-#kernel_path=/Applications/Mathematica.app/Contents/MacOS/MathKernel
-kernel_path=/usr/local/bin/MathKernel
+case $(uname) in
+    Linux)
+        kernel_path=/usr/local/bin/MathKernel
+        ccl=ccl/lx86cl64
+        ;;
+    CYGWIN_NT-[[:digit:]]*.[[:digit:]]*)
+        kernel_path="$(cygpath 'C:\Program Files\Wolfram Research\Mathematica\11.3\MathKernel')"
+        ccl=ccl/wx86cl64
+        ;;
+    Darwin)
+        kernel_path=/Applications/Mathematica.app/Contents/MacOS/MathKernel
+        ccl=ccl/dx86cl64
+        ;;
+    *)
+        echo "$0: Error: Unsupported operating system.">&2
+        exit 1
+        ;;
+esac
 
 test -f "$kernel_path" || {
     echo "$0: Warning: Mathematica kernel not found.">&2
@@ -17,9 +33,6 @@ test -f src/spiroffs-project.lisp || {
     echo "$0: Source code not found. Cannot compile." >&2
     exit 1
 }
-
-#ccl=ccl/dx86cl64
-ccl=ccl
 
 $ccl -l src/spiroffs-project.lisp \
   -e '(save-application "hkm.image" :toplevel-function #'\''main)' \
